### ISSUE TITLE
gtk download

### ISSUE THREAD

**Issue by alnf** [NGSchool2016/ngschool2016-materials#5]
I can't download gtk from [https://software.broadinstitute.org/gatk/download/auth?package=GATK](https://software.broadinstitute.org/gatk/download/auth?package=GATK)

It just shows blank page on both chrome and firefox. Do I need to register in order to get it?

**Comment by lpryszcz** [comment]
Yes, you need to register. Or just copy the source from http://ngschool.local/ngschool-data/src/GATK/
